### ISSUE TITLE
ftp settingでFTPFOLDERがパーセントエンコードされてしまう。

### ISSUE THREAD

**Issue by akmz** [bakueikozo/atomcam_tools#1]
web consoleからだとupload folderのスラッシュが %2Fにエンコードされてしまいディレクトリ指定が出来ない様です。
ex) "/share/web_camera/ebi" -> "%2Fshare%2Fweb_camera%2Febi"

**Comment by bakueikozo** [comment]
報告ありがとうございます。
ログインディレクトリ以下に一階層のみ作ることしか想定してませんでした。
修正予定です。

もうやってるかもしれませんが、hack.iniを直接編集しておくか(WebuiからFTPの項目以外の設定変更ボタンなら設定は壊れません)、サーバー側でユーザー別のログインディレクトリを設定する、などで対処してみてください。

**Comment by bakueikozo** [comment]
1.0rc2で対応しました。不具合があれば再openします。

**Comment by akmz** [comment]
ありがとうございます！
手元で確認できました。
