### ISSUE TITLE
AtomCam2が起動できない問題

### ISSUE THREAD

**Issue by yonp13** [bakueikozo/atomcam_tools#4]
先日新しくAtom Cam2を購入し、当該ツールの導入を試してみましたが、
Atom Camが起動できず、atomcam_toolsの管理画面にもアクセスできない状態です。
何か対策などありましたらお教えいただけると幸いです。

■環境
- デバイス：Atom Cam2
- Firmware：4.58.0.65
- atomcam_tools：v1.0rc2, v1.0rc1　※両方試したが結果は変わらず

■試したこと
- Atom Cam2のアプリでフォーマットしたSDカードのルートディレクトリに「atomcam_tools_1.0rc2.zip」を解凍したファイルをすべて格納　→　Atom Cam2を再起動（USB給電ケーブルの抜線＆再結線）。
- その後、管理画面（http://[ATOMCam2のIPアドレス]:8080/cgi-bin/honeylab.cgi）にアクセスするが、一切応答なし
- Atom Cam2に直接Ping送るが、同様に応答なし
- Atom Cam2本体のLEDは「ステータスライト：オレンジ点灯、赤外線LED：赤点灯」のまま　※30分放置したが変化なし
- Atom Cam2からSDカードを引き抜くと本体が正常起動し、公式App(iOS)からも接続可能になる。
　※atomcam_toolsの管理画面には引き続きアクセスできない。Telnetも不可
- 本体をリセットし、最初から試すが同様の結果になる。

状況は以上になります。
他に推奨手順や対処方法等がありましたらお教えいただけると幸いです。

何卒よろしくお願い致します。

**Comment by mitanosora** [comment]
同じこと起こってカード変えたらうまくいったので相性あるのかもしれません。

**Comment by yonp13** [comment]
@mitanosora
レス有難うございます。
早速、カードを変えて試したところ、見事に起動できました！
（元々、Atom Camで録画も成功していたSDカードでしたので完全に見落としておりました。。）

情報シェアくださり大変感謝いたします。

**Comment by yonp13** [comment]
解決済みのため、クローズさせて頂きます。

**Comment by n2naokun** [comment]
クローズ済みなのでもしかしたらご迷惑かも知れませんが、
先日同じ状態になった時に試してSDカードを交換せずに動作するようになったため
情報の共有をさせていただきます。

複数のAtomCam・AtomCam2に一気に導入するためにスマートフォンにOTGアダプタと
メモリーカードリーダーを接続してAndroid上のファイラーアプリからファイルを
書き込んでいたところAtomCam2にて同様の現象が発生しました。

そのSDカードはAndroid端末に接続した時に表示されるUUIDの一部？が0000-0000になっていました。
他のSDカードはきちんと 4桁-4桁 のUUID？が表示されていました。

SDカードの中身をすべてバックアップした上でPCからSD Association謹製のSD Card Formatterを
使用してフォーマットし直し中身を書き戻した所上手く動作するようになりました。
その状態でAndroid端末に接続し確認したところやはりUUID？が表示されるようになっていました。

あまり覚えてはいませんがもしかしたらこのSDカードだけはAtomCam2上でフォーマットしていたかもしれません。

**Comment by yonp13** [comment]
他の方の参考にもなると思いますのでシェアいただき感謝いたします。
（私も次回再発時にはUUIDの件、確認してみます）

**Comment by toge** [comment]
貴重な情報をありがとうございます。
Atom Cam2(4.58.0.65)で起動しない問題に遭遇し、このissueに辿りつきました。
ここをヒントに試行錯誤したところ以下のようになりました。

1. Windows10 エクスプローラーからフォーマット → ×
2. Windows10 SD Card Formatterからフォーマット → ×
3. Atom Cam2に差してアプリからフォーマット、その上でPCからatomcam toolsを上書き → ○

どれが有効だったのか切り分けできていませんが、ひとまず動くようになりました。
ご参考までに。
